name: todo
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  cupertino_icons: ^1.0.8
  flutter:
    sdk: flutter
  get: ^4.6.6
  flutter_gif: ^0.0.4
  flutter_animated_button: ^2.0.4

  hive: ^2.2.3
  hive_flutter: ^1.1.0
  flutter_slidable: ^3.1.2

dev_dependencies:
  flutter_lints: ^4.0.0
  hive_generator: ^2.0.1
  build_runner: ^2.3.3
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets\gif\gif.gif
